source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'puma', '~> 6.4'
gem 'keplars', '~> 1.10'
gem 'dotenv', '~> 3.1'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'webmock', '~> 3.19'
end
